/**
 * Interfaz para un emoji individual
 */
export interface Emoji {
  nombre: string;
  emoji: string;
}

/**
 * Interfaz para una categoría de emojis
 */
export interface EmojiCategory {
  id: string;
  categoria: string;
  emojis: Emoji[];
}

/**
 * Datos de emojis organizados por categorías
 */
export const EMOJI_DATA: EmojiCategory[] = [
  {
    id: 'rostros_emociones',
    categoria: 'Rostros y Emociones',
    emojis: [
      { nombre: 'Sonriente', emoji: '😀' },
      { nombre: 'Sonriente con ojos sonrientes', emoji: '😊' },
      { nombre: 'Sonriente con lágrimas de alegría', emoji: '😂' },
      { nombre: 'ROFL', emoji: '🤣' },
      { nombre: 'Sonriente con corazones', emoji: '🥰' },
      { nombre: 'Sonriente con 3 corazones', emoji: '😍' },
      { nombre: 'Guiñando un ojo', emoji: '😉' },
      { nombre: 'Besando', emoji: '😘' },
      { nombre: 'Beso con corazón', emoji: '😗' },
      { nombre: 'Beso cerrado', emoji: '😙' },
      { nombre: 'Saboreando', emoji: '😋' },
      { nombre: 'Lengua afuera', emoji: '😛' },
      { nombre: 'Lengua guiñando', emoji: '😜' },
      { nombre: 'Cara loca', emoji: '🤪' },
      { nombre: 'Sonrisa nerviosa', emoji: '😅' },
      { nombre: 'Gota de sudor', emoji: '😓' },
      { nombre: 'Sudando frío', emoji: '😰' },
      { nombre: 'Aliviado', emoji: '😌' },
      { nombre: 'Pensativo', emoji: '🤔' },
      { nombre: 'Cara neutral', emoji: '😐' },
      { nombre: 'Cara sin expresión', emoji: '😑' },
      { nombre: 'Sin boca', emoji: '😶' },
      { nombre: 'Sorprendido', emoji: '😮' },
      { nombre: 'Asombrado', emoji: '😯' },
      { nombre: 'Boca abierta', emoji: '😲' },
      { nombre: 'Sonrojado', emoji: '😳' },
      { nombre: 'Cansado', emoji: '😫' },
      { nombre: 'Agotado', emoji: '😩' },
      { nombre: 'Llorando', emoji: '😢' },
      { nombre: 'Sollozando', emoji: '😭' },
      { nombre: 'Enfadado', emoji: '😠' },
      { nombre: 'Furioso', emoji: '😡' },
      { nombre: 'Asustado', emoji: '😨' },
      { nombre: 'Aterrorizado', emoji: '😱' },
      { nombre: 'Ansioso', emoji: '😰' },
      { nombre: 'Triste', emoji: '☹️' },
      { nombre: 'Confundido', emoji: '😕' },
      { nombre: 'Preocupado', emoji: '😟' },
      { nombre: 'Decepcionado', emoji: '😞' },
      { nombre: 'Abatido', emoji: '😔' },
      { nombre: 'Enfermo', emoji: '🤢' },
      { nombre: 'Vomitando', emoji: '🤮' },
      { nombre: 'Estornudando', emoji: '🤧' },
      { nombre: 'Mareado', emoji: '😵' },
      { nombre: 'Dormido', emoji: '😴' },
      { nombre: 'Zzz', emoji: '💤' },
      { nombre: 'Loco', emoji: '🤯' },
      { nombre: 'Con monóculo', emoji: '🧐' },
      { nombre: 'Nerd', emoji: '🤓' },
      { nombre: 'Con lentes de sol', emoji: '😎' },
      { nombre: 'Estrella', emoji: '🤩' },
      { nombre: 'Fiestero', emoji: '🥳' },
      { nombre: 'Diablo sonriente', emoji: '😈' },
      { nombre: 'Diablo enfadado', emoji: '👿' },
      { nombre: 'Payaso', emoji: '🤡' },
      { nombre: 'Fantasma', emoji: '👻' },
      { nombre: 'Calavera', emoji: '💀' },
      { nombre: 'Calavera cruzada', emoji: '☠️' },
      { nombre: 'Extraterrestre', emoji: '👽' },
      { nombre: 'Robot', emoji: '🤖' },
      { nombre: 'Caca', emoji: '💩' }
    ]
  },
  {
    id: 'gestos_manos',
    categoria: 'Gestos y Manos',
    emojis: [
      { nombre: 'Mano saludando', emoji: '👋' },
      { nombre: 'Mano levantada', emoji: '🤚' },
      { nombre: 'Palma abierta', emoji: '🖐️' },
      { nombre: 'Vulcano', emoji: '🖖' },
      { nombre: 'OK', emoji: '👌' },
      { nombre: 'Victoria', emoji: '✌️' },
      { nombre: 'Dedos cruzados', emoji: '🤞' },
      { nombre: 'Love', emoji: '🤟' },
      { nombre: 'Cuernos', emoji: '🤘' },
      { nombre: 'Llamame', emoji: '🤙' },
      { nombre: 'Apuntando izquierda', emoji: '👈' },
      { nombre: 'Apuntando derecha', emoji: '👉' },
      { nombre: 'Apuntando arriba', emoji: '👆' },
      { nombre: 'Apuntando abajo', emoji: '👇' },
      { nombre: 'Índice arriba', emoji: '☝️' },
      { nombre: 'Pulgar arriba', emoji: '👍' },
      { nombre: 'Pulgar abajo', emoji: '👎' },
      { nombre: 'Puño levantado', emoji: '✊' },
      { nombre: 'Puño', emoji: '👊' },
      { nombre: 'Puño izquierdo', emoji: '🤛' },
      { nombre: 'Puño derecho', emoji: '🤜' },
      { nombre: 'Aplaudiendo', emoji: '👏' },
      { nombre: 'Manos levantadas', emoji: '🙌' },
      { nombre: 'Manos abiertas', emoji: '👐' },
      { nombre: 'Manos juntas', emoji: '🤲' },
      { nombre: 'Apretón de manos', emoji: '🤝' },
      { nombre: 'Rezando', emoji: '🙏' },
      { nombre: 'Escribiendo', emoji: '✍️' },
      { nombre: 'Uñas pintadas', emoji: '💅' },
      { nombre: 'Brazo fuerte', emoji: '💪' }
    ]
  },
  {
    id: 'personas',
    categoria: 'Personas y Cuerpo',
    emojis: [
      { nombre: 'Bebé', emoji: '👶' },
      { nombre: 'Niño', emoji: '🧒' },
      { nombre: 'Niña', emoji: '👧' },
      { nombre: 'Chico', emoji: '👦' },
      { nombre: 'Persona', emoji: '🧑' },
      { nombre: 'Hombre', emoji: '👨' },
      { nombre: 'Mujer', emoji: '👩' },
      { nombre: 'Adulto mayor', emoji: '🧓' },
      { nombre: 'Anciano', emoji: '👴' },
      { nombre: 'Anciana', emoji: '👵' },
      { nombre: 'Persona rubia', emoji: '👱' },
      { nombre: 'Hombre rubio', emoji: '👱‍♂️' },
      { nombre: 'Mujer rubia', emoji: '👱‍♀️' },
      { nombre: 'Persona barbuda', emoji: '🧔' },
      { nombre: 'Príncipe', emoji: '🤴' },
      { nombre: 'Princesa', emoji: '👸' },
      { nombre: 'Policía', emoji: '👮' },
      { nombre: 'Detective', emoji: '🕵️' },
      { nombre: 'Guardia', emoji: '💂' },
      { nombre: 'Constructor', emoji: '👷' },
      { nombre: 'Doctor', emoji: '👨‍⚕️' },
      { nombre: 'Doctora', emoji: '👩‍⚕️' },
      { nombre: 'Científico', emoji: '👨‍🔬' },
      { nombre: 'Científica', emoji: '👩‍🔬' },
      { nombre: 'Profesor', emoji: '👨‍🏫' },
      { nombre: 'Profesora', emoji: '👩‍🏫' },
      { nombre: 'Estudiante', emoji: '👨‍🎓' },
      { nombre: 'Cantante', emoji: '👨‍🎤' },
      { nombre: 'Artista', emoji: '👨‍🎨' },
      { nombre: 'Chef', emoji: '👨‍🍳' },
      { nombre: 'Mecánico', emoji: '👨‍🔧' },
      { nombre: 'Bombero', emoji: '👨‍🚒' },
      { nombre: 'Piloto', emoji: '👨‍✈️' },
      { nombre: 'Astronauta', emoji: '👨‍🚀' },
      { nombre: 'Programador', emoji: '👨‍💻' },
      { nombre: 'Oficinista', emoji: '👨‍💼' }
    ]
  },
  {
    id: 'animales',
    categoria: 'Animales y Naturaleza',
    emojis: [
      { nombre: 'Perro', emoji: '🐶' },
      { nombre: 'Gato', emoji: '🐱' },
      { nombre: 'Ratón', emoji: '🐭' },
      { nombre: 'Hámster', emoji: '🐹' },
      { nombre: 'Conejo', emoji: '🐰' },
      { nombre: 'Zorro', emoji: '🦊' },
      { nombre: 'Oso', emoji: '🐻' },
      { nombre: 'Panda', emoji: '🐼' },
      { nombre: 'Koala', emoji: '🐨' },
      { nombre: 'Tigre', emoji: '🐯' },
      { nombre: 'León', emoji: '🦁' },
      { nombre: 'Vaca', emoji: '🐮' },
      { nombre: 'Cerdo', emoji: '🐷' },
      { nombre: 'Rana', emoji: '🐸' },
      { nombre: 'Mono', emoji: '🐵' },
      { nombre: 'Pollito', emoji: '🐥' },
      { nombre: 'Pájaro', emoji: '🐦' },
      { nombre: 'Pingüino', emoji: '🐧' },
      { nombre: 'Caballo', emoji: '🐴' },
      { nombre: 'Unicornio', emoji: '🦄' },
      { nombre: 'Abeja', emoji: '🐝' },
      { nombre: 'Mariposa', emoji: '🦋' },
      { nombre: 'Caracol', emoji: '🐌' },
      { nombre: 'Mariquita', emoji: '🐞' },
      { nombre: 'Tortuga', emoji: '🐢' },
      { nombre: 'Serpiente', emoji: '🐍' },
      { nombre: 'Dinosaurio', emoji: '🦕' },
      { nombre: 'T-Rex', emoji: '🦖' },
      { nombre: 'Pulpo', emoji: '🐙' },
      { nombre: 'Delfín', emoji: '🐬' },
      { nombre: 'Ballena', emoji: '🐳' },
      { nombre: 'Tiburón', emoji: '🦈' },
      { nombre: 'Pez', emoji: '🐠' },
      { nombre: 'Dragón', emoji: '🐉' }
    ]
  },
  {
    id: 'comida_bebida',
    categoria: 'Comida y Bebida',
    emojis: [
      { nombre: 'Manzana', emoji: '🍎' },
      { nombre: 'Banana', emoji: '🍌' },
      { nombre: 'Sandía', emoji: '🍉' },
      { nombre: 'Uvas', emoji: '🍇' },
      { nombre: 'Fresa', emoji: '🍓' },
      { nombre: 'Cereza', emoji: '🍒' },
      { nombre: 'Piña', emoji: '🍍' },
      { nombre: 'Aguacate', emoji: '🥑' },
      { nombre: 'Berenjena', emoji: '🍆' },
      { nombre: 'Zanahoria', emoji: '🥕' },
      { nombre: 'Maíz', emoji: '🌽' },
      { nombre: 'Pizza', emoji: '🍕' },
      { nombre: 'Hamburguesa', emoji: '🍔' },
      { nombre: 'Hot dog', emoji: '🌭' },
      { nombre: 'Taco', emoji: '🌮' },
      { nombre: 'Burrito', emoji: '🌯' },
      { nombre: 'Sushi', emoji: '🍣' },
      { nombre: 'Espagueti', emoji: '🍝' },
      { nombre: 'Pollo', emoji: '🍗' },
      { nombre: 'Carne', emoji: '🥩' },
      { nombre: 'Tocino', emoji: '🥓' },
      { nombre: 'Pan', emoji: '🍞' },
      { nombre: 'Croissant', emoji: '🥐' },
      { nombre: 'Panqueques', emoji: '🥞' },
      { nombre: 'Waffle', emoji: '🧇' },
      { nombre: 'Queso', emoji: '🧀' },
      { nombre: 'Huevo', emoji: '🥚' },
      { nombre: 'Helado', emoji: '🍦' },
      { nombre: 'Dona', emoji: '🍩' },
      { nombre: 'Galleta', emoji: '🍪' },
      { nombre: 'Pastel', emoji: '🍰' },
      { nombre: 'Tarta', emoji: '🎂' },
      { nombre: 'Cupcake', emoji: '🧁' },
      { nombre: 'Chocolate', emoji: '🍫' },
      { nombre: 'Caramelo', emoji: '🍬' },
      { nombre: 'Paleta', emoji: '🍭' },
      { nombre: 'Café', emoji: '☕' },
      { nombre: 'Té', emoji: '🍵' },
      { nombre: 'Mate', emoji: '🧉' },
      { nombre: 'Bebida', emoji: '🥤' },
      { nombre: 'Jugo', emoji: '🧃' },
      { nombre: 'Cerveza', emoji: '🍺' },
      { nombre: 'Vino', emoji: '🍷' },
      { nombre: 'Champagne', emoji: '🍾' },
      { nombre: 'Cóctel', emoji: '🍸' },
      { nombre: 'Margarita', emoji: '🍹' }
    ]
  },
  {
    id: 'actividades',
    categoria: 'Actividades y Deportes',
    emojis: [
      { nombre: 'Fútbol', emoji: '⚽' },
      { nombre: 'Baloncesto', emoji: '🏀' },
      { nombre: 'Béisbol', emoji: '⚾' },
      { nombre: 'Tenis', emoji: '🎾' },
      { nombre: 'Voleibol', emoji: '🏐' },
      { nombre: 'Rugby', emoji: '🏉' },
      { nombre: 'Golf', emoji: '⛳' },
      { nombre: 'Billar', emoji: '🎱' },
      { nombre: 'Ping pong', emoji: '🏓' },
      { nombre: 'Bádminton', emoji: '🏸' },
      { nombre: 'Hockey', emoji: '🏑' },
      { nombre: 'Natación', emoji: '🏊' },
      { nombre: 'Surf', emoji: '🏄' },
      { nombre: 'Esquí', emoji: '⛷️' },
      { nombre: 'Snowboard', emoji: '🏂' },
      { nombre: 'Ciclismo', emoji: '🚴' },
      { nombre: 'Escalada', emoji: '🧗' },
      { nombre: 'Yoga', emoji: '🧘' },
      { nombre: 'Pesas', emoji: '🏋️' },
      { nombre: 'Boxeo', emoji: '🥊' },
      { nombre: 'Artes marciales', emoji: '🥋' },
      { nombre: 'Música', emoji: '🎵' },
      { nombre: 'Guitarra', emoji: '🎸' },
      { nombre: 'Piano', emoji: '🎹' },
      { nombre: 'Saxofón', emoji: '🎷' },
      { nombre: 'Trompeta', emoji: '🎺' },
      { nombre: 'Violín', emoji: '🎻' },
      { nombre: 'Batería', emoji: '🥁' },
      { nombre: 'Micrófono', emoji: '🎤' },
      { nombre: 'Auriculares', emoji: '🎧' },
      { nombre: 'Película', emoji: '🎬' },
      { nombre: 'Cine', emoji: '🎥' },
      { nombre: 'Arte', emoji: '🎨' },
      { nombre: 'Videojuego', emoji: '🎮' },
      { nombre: 'Ajedrez', emoji: '♟️' },
      { nombre: 'Dados', emoji: '🎲' }
    ]
  },
  {
    id: 'viajes_lugares',
    categoria: 'Viajes y Lugares',
    emojis: [
      { nombre: 'Coche', emoji: '🚗' },
      { nombre: 'Taxi', emoji: '🚕' },
      { nombre: 'Bus', emoji: '🚌' },
      { nombre: 'Tren', emoji: '🚆' },
      { nombre: 'Metro', emoji: '🚇' },
      { nombre: 'Avión', emoji: '✈️' },
      { nombre: 'Helicóptero', emoji: '🚁' },
      { nombre: 'Barco', emoji: '🚢' },
      { nombre: 'Bicicleta', emoji: '🚲' },
      { nombre: 'Moto', emoji: '🏍️' },
      { nombre: 'Scooter', emoji: '🛵' },
      { nombre: 'Ambulancia', emoji: '🚑' },
      { nombre: 'Bomberos', emoji: '🚒' },
      { nombre: 'Policía', emoji: '🚓' },
      { nombre: 'Cohete', emoji: '🚀' },
      { nombre: 'Casa', emoji: '🏠' },
      { nombre: 'Edificio', emoji: '🏢' },
      { nombre: 'Escuela', emoji: '🏫' },
      { nombre: 'Hospital', emoji: '🏥' },
      { nombre: 'Hotel', emoji: '🏨' },
      { nombre: 'Banco', emoji: '🏦' },
      { nombre: 'Tienda', emoji: '🏪' },
      { nombre: 'Castillo', emoji: '🏰' },
      { nombre: 'Torre', emoji: '🗼' },
      { nombre: 'Estatua Libertad', emoji: '🗽' },
      { nombre: 'Pirámide', emoji: '🗿' },
      { nombre: 'Playa', emoji: '🏖️' },
      { nombre: 'Montaña', emoji: '⛰️' },
      { nombre: 'Volcán', emoji: '🌋' },
      { nombre: 'Desierto', emoji: '🏜️' },
      { nombre: 'Isla', emoji: '🏝️' },
      { nombre: 'Camping', emoji: '🏕️' },
      { nombre: 'Mapa', emoji: '🗺️' },
      { nombre: 'Brújula', emoji: '🧭' }
    ]
  },
  {
    id: 'objetos',
    categoria: 'Objetos',
    emojis: [
      { nombre: 'Teléfono', emoji: '📱' },
      { nombre: 'Computadora', emoji: '💻' },
      { nombre: 'Teclado', emoji: '⌨️' },
      { nombre: 'Mouse', emoji: '🖱️' },
      { nombre: 'Impresora', emoji: '🖨️' },
      { nombre: 'Cámara', emoji: '📷' },
      { nombre: 'Video cámara', emoji: '📹' },
      { nombre: 'TV', emoji: '📺' },
      { nombre: 'Reloj', emoji: '⌚' },
      { nombre: 'Despertador', emoji: '⏰' },
      { nombre: 'Cronómetro', emoji: '⏱️' },
      { nombre: 'Bombilla', emoji: '💡' },
      { nombre: 'Linterna', emoji: '🔦' },
      { nombre: 'Vela', emoji: '🕯️' },
      { nombre: 'Libro', emoji: '📖' },
      { nombre: 'Libros', emoji: '📚' },
      { nombre: 'Cuaderno', emoji: '📓' },
      { nombre: 'Lápiz', emoji: '✏️' },
      { nombre: 'Pluma', emoji: '🖊️' },
      { nombre: 'Pincel', emoji: '🖌️' },
      { nombre: 'Tijeras', emoji: '✂️' },
      { nombre: 'Llave', emoji: '🔑' },
      { nombre: 'Candado', emoji: '🔒' },
      { nombre: 'Martillo', emoji: '🔨' },
      { nombre: 'Hacha', emoji: '🪓' },
      { nombre: 'Destornillador', emoji: '🪛' },
      { nombre: 'Lupa', emoji: '🔍' },
      { nombre: 'Batería', emoji: '🔋' },
      { nombre: 'Enchufe', emoji: '🔌' },
      { nombre: 'Dinero', emoji: '💰' },
      { nombre: 'Billete', emoji: '💵' },
      { nombre: 'Tarjeta', emoji: '💳' },
      { nombre: 'Regalo', emoji: '🎁' },
      { nombre: 'Globo', emoji: '🎈' },
      { nombre: 'Confeti', emoji: '🎉' },
      { nombre: 'Corona', emoji: '👑' },
      { nombre: 'Trofeo', emoji: '🏆' },
      { nombre: 'Medalla', emoji: '🏅' }
    ]
  },
  {
    id: 'simbolos',
    categoria: 'Símbolos',
    emojis: [
      { nombre: 'Corazón rojo', emoji: '❤️' },
      { nombre: 'Corazón naranja', emoji: '🧡' },
      { nombre: 'Corazón amarillo', emoji: '💛' },
      { nombre: 'Corazón verde', emoji: '💚' },
      { nombre: 'Corazón azul', emoji: '💙' },
      { nombre: 'Corazón morado', emoji: '💜' },
      { nombre: 'Corazón negro', emoji: '🖤' },
      { nombre: 'Corazón blanco', emoji: '🤍' },
      { nombre: 'Corazón roto', emoji: '💔' },
      { nombre: 'Corazones', emoji: '💕' },
      { nombre: 'Corazón brillante', emoji: '💖' },
      { nombre: 'Corazón creciendo', emoji: '💗' },
      { nombre: 'Corazón latiendo', emoji: '💓' },
      { nombre: 'Corazón girando', emoji: '💞' },
      { nombre: 'Estrella', emoji: '⭐' },
      { nombre: 'Estrella brillante', emoji: '✨' },
      { nombre: 'Fuego', emoji: '🔥' },
      { nombre: 'Rayo', emoji: '⚡' },
      { nombre: 'Check', emoji: '✅' },
      { nombre: 'X', emoji: '❌' },
      { nombre: 'Prohibido', emoji: '🚫' },
      { nombre: 'Advertencia', emoji: '⚠️' },
      { nombre: 'Interrogación', emoji: '❓' },
      { nombre: 'Exclamación', emoji: '❗' },
      { nombre: 'Flecha arriba', emoji: '⬆️' },
      { nombre: 'Flecha abajo', emoji: '⬇️' },
      { nombre: 'Flecha izquierda', emoji: '⬅️' },
      { nombre: 'Flecha derecha', emoji: '➡️' },
      { nombre: 'Reciclaje', emoji: '♻️' },
      { nombre: 'Paz', emoji: '☮️' },
      { nombre: 'Yin Yang', emoji: '☯️' },
      { nombre: 'Cruz', emoji: '✝️' },
      { nombre: 'Infinito', emoji: '♾️' },
      { nombre: '100', emoji: '💯' },
      { nombre: 'OK', emoji: '🆗' },
      { nombre: 'Nuevo', emoji: '🆕' },
      { nombre: 'Gratis', emoji: '🆓' },
      { nombre: 'Cool', emoji: '🆒' }
    ]
  },
  {
    id: 'naturaleza_clima',
    categoria: 'Naturaleza y Clima',
    emojis: [
      { nombre: 'Sol', emoji: '☀️' },
      { nombre: 'Nube', emoji: '☁️' },
      { nombre: 'Lluvia', emoji: '🌧️' },
      { nombre: 'Tormenta', emoji: '⛈️' },
      { nombre: 'Rayo', emoji: '⚡' },
      { nombre: 'Nieve', emoji: '❄️' },
      { nombre: 'Muñeco nieve', emoji: '⛄' },
      { nombre: 'Viento', emoji: '💨' },
      { nombre: 'Tornado', emoji: '🌪️' },
      { nombre: 'Arcoíris', emoji: '🌈' },
      { nombre: 'Luna', emoji: '🌙' },
      { nombre: 'Luna llena', emoji: '🌕' },
      { nombre: 'Estrella', emoji: '⭐' },
      { nombre: 'Cometa', emoji: '☄️' },
      { nombre: 'Planeta', emoji: '🪐' },
      { nombre: 'Tierra', emoji: '🌍' },
      { nombre: 'Árbol', emoji: '🌳' },
      { nombre: 'Palmera', emoji: '🌴' },
      { nombre: 'Cactus', emoji: '🌵' },
      { nombre: 'Flor', emoji: '🌸' },
      { nombre: 'Rosa', emoji: '🌹' },
      { nombre: 'Girasol', emoji: '🌻' },
      { nombre: 'Tulipán', emoji: '🌷' },
      { nombre: 'Hoja', emoji: '🍃' },
      { nombre: 'Hojas otoño', emoji: '🍂' },
      { nombre: 'Trébol', emoji: '☘️' },
      { nombre: 'Champiñón', emoji: '🍄' }
    ]
  },
  {
    id: 'banderas',
    categoria: 'Banderas',
    emojis: [
      { nombre: 'Bandera blanca', emoji: '🏳️' },
      { nombre: 'Bandera negra', emoji: '🏴' },
      { nombre: 'Bandera arcoíris', emoji: '🏳️‍🌈' },
      { nombre: 'Bandera pirata', emoji: '🏴‍☠️' },
      { nombre: 'Argentina', emoji: '🇦🇷' },
      { nombre: 'Brasil', emoji: '🇧🇷' },
      { nombre: 'Chile', emoji: '🇨🇱' },
      { nombre: 'Colombia', emoji: '🇨🇴' },
      { nombre: 'España', emoji: '🇪🇸' },
      { nombre: 'Estados Unidos', emoji: '🇺🇸' },
      { nombre: 'Francia', emoji: '🇫🇷' },
      { nombre: 'Italia', emoji: '🇮🇹' },
      { nombre: 'Japón', emoji: '🇯🇵' },
      { nombre: 'México', emoji: '🇲🇽' },
      { nombre: 'Reino Unido', emoji: '🇬🇧' },
      { nombre: 'Alemania', emoji: '🇩🇪' },
      { nombre: 'China', emoji: '🇨🇳' },
      { nombre: 'Canadá', emoji: '🇨🇦' },
      { nombre: 'Australia', emoji: '🇦🇺' },
      { nombre: 'Portugal', emoji: '🇵🇹' }
    ]
  }
];
